### ISSUE TITLE
Location of .travis.yml

### ISSUE THREAD

**Issue by tlenclos** [TheSmiths/ts.boilerplate#1]
Hi guys !
Nice project, I'm trying it with a new project and after pushing the code on github and setting travis to build, the file `.travis.yml` is in the project subdirectory (so it can't build with travis).

I think it should be in the root of the repository and cd in the project dir while building ?

Also I tried this solution and the build is failing on travis: https://travis-ci.org/tlenclos/PhotoTrip/builds/66371645.

Thanks,
Thibault.

**Comment by KtorZ** [comment]
Hey Thibault, 

Nice to see that someone is interested and in fact, using it ^^.. Keep in mind that the project is still experimental; We are adding features as long as we discover the need for them. 
Feel free to suggest any idea or comment, you're welcome.

Indeed, your project does not build, and mainly because of two reasons:
- There is a fix with Jasmine test that I haven't publish yet. 
- The Calabash testing procedure is trying to upload any screenshot made during tests to Cloudinary (a cloud image hosting center) and thus, try to connect to your account through a environment key. If the key isn't supplied, it will failed. Again, I will make an update in the readme to explain this and, above all, I will allow the test to run even if there is no key!

I am working on it; Once published, please try it and let me know if you still encounter any problem. 

By the by, adding a `cd <your_project>` to the **.travis.yml** file was in your case, the right thing to do!

**Comment by tlenclos** [comment]
Nice ! I'll try later then ;)

**Comment by KtorZ** [comment]
Okay, this might be okay for you by now. 
Update the module with npm running `npm update -g thesmiths/ts.boilerplate` or simply `npm install -g thesmiths/ts.boilerplate`.

A new command has been added to the CLI, "update". It will allow you to update the different gulpfiles of an existing project. New projects will be automatically bundled with the new version, but your old ones might need this refresh. Just go in the root folder of your project and run `ts-boilerplate update`.

Also, I've made some changes in an other related node modules (gulp-additional-utils). If you want to use gulp in your local system, update this module before running any gulp command. (It won't be a problem for travis which will re-install the latest version during the next build). 

Let me know if you encounter any issue... it should work.
